version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome-dbug:
    image: selenium/node-chrome-debug:3.141.59-20200525
    deploy:
      replicas: 5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444  
    ports:
      - "5900:5900"
  firefox-dbug:
    image: selenium/node-firefox-debug:3.141.59-20200525
    deploy:
      replicas: 5
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5800:5900"
  rm_wdio-framework:
    image: node:12.13.1
    volumes:
      - ./:/tmp
    container_name: rm_wdiofw_docrz
    working_dir: /tmp
    command: bash -c "npm install && npm run docker_grid_jenkins"
    depends_on:
      - selenium-hub
      - firefox-dbug

    depends_on:
      - selenium-hub
      - firefox-dbug
      - chrome-dbug
   